### ISSUE TITLE
stjerm sometimes has no focus when calles

### ISSUE THREAD

**Issue by justfortherec** [stjerm/stjerm#15]
Hi,

Often times stjerm isn't focused when it gets called with the shortcut key. That means: Is shows up but the cursor is still in another window. I first have to click on the stjerm window to activate it.
### Steps to reproduce:
1. Exit stjerm
2. start stjerm (see my .Xdefaults below)
3. Press F12 [Now stjerm has focus. I can start typing. Everything is alright.]
4. Hide stjerm by focusing another window: e.g. gedit.
5. Type something in gedit
6. Press F12
7. Type 'something'
### What should happen:

stjerm shows up and has focus. 'something' should appear in stjerm
### What really happens:

stjerm shows up but gedit still has focus. 'something' appears in gedit

```
~$ cat .Xdefaults 
stjerm.key: f12
stjerm.font: Ubuntu Mono 13
stjerm.opacity: 80
```

**Comment by alpinito1** [comment]
Hello folks,

Do you know what would be the trick when Compiz is not being used? I am using the defaults setting of ubuntu 14.04 (Unity) I guess.

Thank you!
